### ISSUE TITLE
A Problem when Using chrono preprocessor

### ISSUE THREAD

**Issue by jzhongap** [Concrete-Chrono-Development/chrono-preprocessor#3]
Hi Matthew, I am a graduate student working with Tianju. I'm having some problems when using chrono preprocessor. I successfully installed the chronoConcrete according to the process and called the module in FreeCAD. But after I set a series of parameters, the error "Tetgen failed during tetrahedralization" will be displayed. At the same time, the file it requires, LDPMgeo0002D.1.ele, cannot be found in the corresponding folder, but only the LDPMgeo0002D.mesh file. I repeated this process in 3 different computers, but the errors it shows are the same. How should I solve this problem? The parameters are shown in this file.
[chronoWorkbench_parameter.zip](https://github.com/Concrete-Chrono-Development/chrono-preprocessor/files/14062164/chronoWorkbench_parameter.zip)

**Comment by jzhongap** [comment]
Thank you for your reply.

- All the three computers are the same Window 11 system, I encountered this error when I input the parameters in FreeCAD/ chronoConcrete Mod and click the Generate Model button. It seems the mesh process can be done successfully, but failed in tetgen.

- When I run this command, an error box pop out showing the following message: Command execution cannot continue because ucrtbased.dll is not found. Reinstalling may resolve this issue. As is attatched in this comment.
<img width="587" alt="tetgen - help_output" src="https://github.com/Concrete-Chrono-Development/chrono-preprocessor/assets/146326816/1e2fcec3-0b89-43a8-841d-7757d95fc58d">

I hope these answers can help you.

Zhong Jiawei

**Comment by mtroemner** [comment]
This does help quite a bit. I have one additional question and then two potential solutions for you to try:

- Do you have Visual Studio installed on your PC? If so, which version, and do you have the C++ module installed as well?
- Please navigate to "C:\Windows\System32" and see if there is a file `ucrtbase.dll` located there. If so copy it into your tetgen folder and try to run your FreeCAD generation again.
- If you do not have that DLL in your system32, then download the DLL from [here](https://www.dll-files.com/ucrtbase.dll.html) (just select the most recent 32 or 64 bit, depending on your OS). Try placing that in the folder next to your tetgen and re-run the generation. 

Let me know how that goes

**Comment by jzhongap** [comment]
I tried the solutions you provided, and here are the answers and outcomes:
- No, I don't have Visual Studio installed on my PC, and the same as the other two computers. Maybe I need to install one?
- I downloaded one DLL file from this link and place it in the corresponding folder, there is still the same error when re-running the generation in FreeCAD software. However, when I run `tetgen -help` again in tetgen folder, the output is like this:
<img width="603" alt="tetgen - help_output1" src="https://github.com/Concrete-Chrono-Development/chrono-preprocessor/assets/146326816/4f45a592-eefd-4948-aa2e-93a91ad05d54">

**Comment by mtroemner** [comment]
Sorry for the delay getting back to you. Now that you have Tetgen working (via the DLL file), there should be no need for Visual Studio, that was just another technique to get Tetgen to work. 

This is very strange that you still have the failure during generation on FreeCAD. Could you please try running the generation again using the same parameters you originally sent in this thread and respond to this comment with the entire output from your Report window? (Report Window is at the bottom left of your FreeCAD screen). If there is a lot of text, you may need to copy it into a text file to upload it here.

**Comment by jzhongap** [comment]
Sure, I use the previous parameters to repeat the generation process and here are the output from FreeCAD:
[FreeCAD_errors.txt](https://github.com/Concrete-Chrono-Development/chrono-preprocessor/files/14174740/FreeCAD_errors.txt)
In addition, I also found a new phenomenon that, when i try to run my tetgen.exe to test the given file example.poly using the command `.\tetgen.exe -p example.poly`, and the results turn out that I don't have enough memory, as is shown in the screenshot:
<img width="656" alt="tetgen_error" src="https://github.com/Concrete-Chrono-Development/chrono-preprocessor/assets/146326816/873aef75-11ad-4cd4-b429-8a495069545b">
I wish this can also help in finding the problems.

**Comment by mtroemner** [comment]
That does help in demonstrating that something is still wrong with Tetgen on your PCs even though the Help information opens fine. That poly example should only take a couple of mb of ram and less than 2-3 seconds to run. At this point I suggest we abandon the FreeCAD interface for now and focus on getting a Tetgen exe file to work, then we can go back to FreeCAD. I also reviewed your complete text output and there is one other minor discrepancy with my log; but, I suspect this is related to Tetgen as well. 

Below I have included Tetgen's official instructions for compiling their code, as well as two alternative links with sets of instructions that include more details. If you would like, as a final test before compiling the code, I have also included in the final link a GitHub repository with several pre-compiled Tetgen binaries; you could see if any of those happen to work.

- https://wias-berlin.de/software/tetgen/1.5/doc/manual/manual004.html#:~:text=To%20compile%20TetGen%2C%20use%20a,be%20embedded%20into%20another%20program.
- https://github.com/dash-orlando/geovar/tree/master/tetgen1.5.1
- https://www.youtube.com/watch?v=FR5k_al4cQw
- https://github.com/JuliaGeometry/tetgen.dependency/tree/master

**Comment by jzhongap** [comment]
Sorry for my late reply, I've tried these ways above including re-compiling a new tetgen.exe file and trying several tetgen.exe files, and give them permission to get the memory in the folder, I find the new tetgens can be used successfully on example.poly and even LDPMgeo0002D.mesh if I proceed it by using command, as is shown in the screenshots.

<img width="268" alt="Success example on example" src="https://github.com/Concrete-Chrono-Development/chrono-preprocessor/assets/146326816/79a23b20-8af1-4e1b-98f9-33af38ab6009">

<img width="287" alt="Success example on LDPMgeo002D" src="https://github.com/Concrete-Chrono-Development/chrono-preprocessor/assets/146326816/922f4beb-3103-4a76-9b4d-989f6a84ae3a">

However, the problem still exists that the FreeCAD cannot properly call tetgen and it seems the tetgen still can't generate the files or have troubles putting them into the right folder. So I think it maybe due to the lack of connection among folders. May I ask what is your settings in permission of files I/O and what maybe helpful in solving this kind of problem?

I am very sorry for troubling you again.

**Comment by mtroemner** [comment]
Sorry for the delay in my response. I now notice that you have your chronoConcrete Workbench installed in the Program Files directory rather than the AppData per the [Readme](https://github.com/Concrete-Chrono-Development/chrono-preprocessor/blob/main/wiki/usage-instructions/installation-and-setup-1.md). Could you please try moving all of the files to see if that helps the input/output permissions?

From:
- C:\Program Files\FreeCAD 0.20\Mod\chronoConcrete

To:
- C:\Users\______\AppData\Roaming\FreeCAD\Mod\chronoConcrete

Alternatively, instead of moving the folder, you may be able to verify the permissions issue by running FreeCAD as an Administrator, or ensuring that all of the files in your chronoConcrete have Read and Write access available for all users and all applications.

**Comment by mtroemner** [comment]
Great! I will close this Issue; but reach out if you find any further problems.
