### ISSUE TITLE
multi-material option

### ISSUE THREAD

**Issue by YuhuiSunshine** [Concrete-Chrono-Development/chrono-preprocessor#4]
Hi Matthew,
When I was running freeCAD by turning on the multi-material option and using the fast generation option, I encountered the issue: 
![image (2)](https://github.com/Concrete-Chrono-Development/chrono-preprocessor/assets/75552919/d3c0e9dc-d9ed-4740-ab65-203d5302eb9c)

Thanks for your help

**Comment by mtroemner** [comment]
I have updated the code to no longer assume that the work bench is installed in ones AppData directory and called chronoConcrete. This should allow for greater flexibility in installations. Please try pulling the code and running again.

**Comment by YuhuiSunshine** [comment]
Thanks for your modification, Matthew. When I used the updated code, the following error appeared. When the Maximum iterations per particle is 50000, we have the first error. When I changed it from 50000 to 1000000, the second image appeared. It was stuck in there. 

![1](https://github.com/Concrete-Chrono-Development/chrono-preprocessor/assets/75552919/3da44483-2a27-43fe-b643-a6620b98abc6)
![2](https://github.com/Concrete-Chrono-Development/chrono-preprocessor/assets/75552919/192dfdce-166c-459c-a92d-9f8ad0fd72ac)

**Comment by mtroemner** [comment]
This appears to be working correctly but that maybe too many particles are trying to be fit into the box (so increasing the Maximum Iterations it keeps trying but does not find a place to put the particles). Please double-check the input numbers for the example I previously sent; when it generates it should only produce ~1,780 particles per material not ~2,500. I've included the images again (as a reminder, you will need to change the .txt extension to .img)

![image](https://github.com/Concrete-Chrono-Development/chrono-preprocessor/assets/31108019/37414272-66dc-49dd-9a57-d17dfcdc4854)
![image (1)](https://github.com/Concrete-Chrono-Development/chrono-preprocessor/assets/31108019/51f29c27-e2fd-4168-afaf-e05f7254e85e)
